function Swipe(o,e){function u(){i=c.children;z=i.length;if(i.length<2)e.continuous=!1;if(m.transitions&&e.continuous&&i.length<3)c.appendChild(i[0].cloneNode(!0)),c.appendChild(c.children[1].cloneNode(!0)),i=c.children;k=Array(i.length);d=o.getBoundingClientRect().width||o.offsetWidth;c.style.width=i.length*d+"px";for(var b=i.length;b--;){var n=i[b];n.style.width=d+"px";n.setAttribute("data-index",b);if(m.transitions)n.style.left=b*-d+"px",g(b,a>b?-d:a<b?d:0,0)}e.continuous&&m.transitions&&(g(h(a-
1),-d,0),g(h(a+1),d,0));if(!m.transitions)c.style.left=a*-d+"px";o.style.visibility="visible"}function v(){e.continuous?t(a+1):a<i.length-1&&t(a+1)}function h(b){return(i.length+b%i.length)%i.length}function t(b,n){if(a!=b){if(m.transitions){var c=Math.abs(a-b)/(a-b);if(e.continuous){var f=c,c=-k[h(b)]/d;c!==f&&(b=-c*i.length+b)}for(f=Math.abs(a-b)-1;f--;)g(h((b>a?b:a)-f-1),d*c,0);b=h(b);g(a,d*c,n||l);g(b,0,n||l);e.continuous&&g(h(b-c),-(d*c),0)}else b=h(b),A(a*-d,b*-d,n||l);a=b;c=e.callback&&e.callback(a,
i[a]);setTimeout(c||w,0)}}function g(b,a,c){p(b,a,c);k[b]=a}function p(b,a,c){var n;if(n=(b=i[b])&&b.style,b=n)b.webkitTransitionDuration=b.MozTransitionDuration=b.msTransitionDuration=b.OTransitionDuration=b.transitionDuration=c+"ms",b.webkitTransform="translate("+a+"px,0)translateZ(0)",b.msTransform=b.MozTransform=b.OTransform="translateX("+a+"px)"}function A(b,d,f){if(f)var g=+new Date,h=setInterval(function(){var j=+new Date-g;j>f?(c.style.left=d+"px",q&&(x=setTimeout(v,q)),e.transitionEnd&&e.transitionEnd.call(event,
a,i[a]),clearInterval(h)):c.style.left=(d-b)*(Math.floor(j/f*100)/100)+b+"px"},4);else c.style.left=d+"px"}function r(){q=0;clearTimeout(x)}var w=function(){},m={addEventListener:!!window.addEventListener,touch:"ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,transitions:function(b){var a=["transitionProperty","WebkitTransition","MozTransition","OTransition","msTransition"],c;for(c in a)if(b.style[a[c]]!==void 0)return!0;return!1}(document.createElement("swipe"))};
if(o){var c=o.children[0],i,k,d,z,e=e||{},a=parseInt(e.startSlide,10)||0,l=e.speed||300;e.continuous=e.continuous!==void 0?e.continuous:!0;var q=e.auto||0,x,y={},f={},s,j={handleEvent:function(a){switch(a.type){case "touchstart":this.start(a);break;case "touchmove":this.move(a);break;case "touchend":var c=this.end(a);setTimeout(c||w,0);break;case "webkitTransitionEnd":case "msTransitionEnd":case "oTransitionEnd":case "otransitionend":case "transitionend":c=this.transitionEnd(a);setTimeout(c||w,0);
break;case "resize":setTimeout(u||w,0)}e.stopPropagation&&a.stopPropagation()},start:function(a){a=a.touches[0];y={x:a.pageX,y:a.pageY,time:+new Date};s=void 0;f={};c.addEventListener("touchmove",this,!1);c.addEventListener("touchend",this,!1)},move:function(b){if(!(b.touches.length>1||b.scale&&b.scale!==1)){e.disableScroll&&b.preventDefault();var c=b.touches[0];f={x:c.pageX-y.x,y:c.pageY-y.y};typeof s=="undefined"&&(s=!!(s||Math.abs(f.x)<Math.abs(f.y)));s||(b.preventDefault(),r(),e.continuous?(p(h(a-
1),f.x+k[h(a-1)],0),p(a,f.x+k[a],0),p(h(a+1),f.x+k[h(a+1)],0)):(f.x/=!a&&f.x>0||a==i.length-1&&f.x<0?Math.abs(f.x)/d+1:1,p(a-1,f.x+k[a-1],0),p(a,f.x+k[a],0),p(a+1,f.x+k[a+1],0)))}},end:function(){var b=Number(+new Date-y.time)<250&&Math.abs(f.x)>20||Math.abs(f.x)>d/2,n=!a&&f.x>0||a==i.length-1&&f.x<0;e.continuous&&(n=!1);var m=f.x<0;s||(b&&!n?(m?(e.continuous?(g(h(a-1),-d,0),g(h(a+2),d,0)):g(a-1,-d,0),g(a,k[a]-d,l),g(h(a+1),k[h(a+1)]-d,l),a=h(a+1)):(e.continuous?(g(h(a+1),d,0),g(h(a-2),-d,0)):g(a+
1,d,0),g(a,k[a]+d,l),g(h(a-1),k[h(a-1)]+d,l),a=h(a-1)),e.callback&&e.callback(a,i[a])):e.continuous?(g(h(a-1),-d,l),g(a,0,l),g(h(a+1),d,l)):(g(a-1,-d,l),g(a,0,l),g(a+1,d,l)));c.removeEventListener("touchmove",j,!1);c.removeEventListener("touchend",j,!1)},transitionEnd:function(b){parseInt(b.target.getAttribute("data-index"),10)==a&&(q&&(x=setTimeout(v,q)),e.transitionEnd&&e.transitionEnd.call(b,a,i[a]))}};u();q&&(x=setTimeout(v,q));m.addEventListener?(m.touch&&c.addEventListener("touchstart",j,!1),
m.transitions&&(c.addEventListener("webkitTransitionEnd",j,!1),c.addEventListener("msTransitionEnd",j,!1),c.addEventListener("oTransitionEnd",j,!1),c.addEventListener("otransitionend",j,!1),c.addEventListener("transitionend",j,!1)),window.addEventListener("resize",j,!1)):window.onresize=function(){u()};return{setup:function(){u()},slide:function(a,c){r();t(a,c)},prev:function(){r();e.continuous?t(a-1):a&&t(a-1)},next:function(){r();v()},stop:function(){r()},getPos:function(){return a},getNumSlides:function(){return z},
kill:function(){r();c.style.width="";c.style.left="";for(var a=i.length;a--;){var d=i[a];d.style.width="";d.style.left="";m.transitions&&p(a,0,0)}m.addEventListener?(c.removeEventListener("touchstart",j,!1),c.removeEventListener("webkitTransitionEnd",j,!1),c.removeEventListener("msTransitionEnd",j,!1),c.removeEventListener("oTransitionEnd",j,!1),c.removeEventListener("otransitionend",j,!1),c.removeEventListener("transitionend",j,!1),window.removeEventListener("resize",j,!1)):window.onresize=null}}}}
if(window.jQuery||window.Zepto)(function(o){o.fn.Swipe=function(e){return this.each(function(){o(this).data("Swipe",new Swipe(o(this)[0],e))})}})(window.jQuery||window.Zepto);
